"""Canonical enumerations defined by the Phase 0 contracts."""

from enum import Enum


class UserStoryStatus(str, Enum):
    PROPOSED = "PROPOSED"
    PLANNED = "PLANNED"
    BLOCKED = "BLOCKED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    IMPLEMENTED = "IMPLEMENTED"
    TESTING = "TESTING"
    REVIEW = "REVIEW"
    CERTIFICATION = "CERTIFICATION"
    CERTIFIED = "CERTIFIED"
    REJECTED = "REJECTED"
    REMEDIATION_REQUIRED = "REMEDIATION_REQUIRED"
    CANCELLED = "CANCELLED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReadinessClassification(str, Enum):
    READY = "READY"
    WAITING_DEPENDENCIES = "WAITING_DEPENDENCIES"
    BLOCKED = "BLOCKED"
    INELIGIBLE = "INELIGIBLE"
    TERMINAL = "TERMINAL"


class DeferredReason(str, Enum):
    BLOCKED = "BLOCKED"
    INELIGIBLE = "INELIGIBLE"
    TERMINAL_SATISFIED = "TERMINAL_SATISFIED"
    TERMINAL_UNSATISFIED = "TERMINAL_UNSATISFIED"
    UNPLANNABLE_DEPENDENCY = "UNPLANNABLE_DEPENDENCY"


class ConflictClassification(str, Enum):
    SAFE = "SAFE"
    CONFLICT = "CONFLICT"
    UNKNOWN = "UNKNOWN"


class ConflictReason(str, Enum):
    PATH_OVERLAP = "PATH_OVERLAP"
    SCOPE_AMBIGUOUS = "SCOPE_AMBIGUOUS"
    SCOPE_UNSPECIFIED = "SCOPE_UNSPECIFIED"


class GateResult(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CertificationResult(str, Enum):
    CERTIFIED = "CERTIFIED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class EvidenceType(str, Enum):
    COMMAND_RESULT = "COMMAND_RESULT"
    TEST_RESULT = "TEST_RESULT"
    GIT_STATE = "GIT_STATE"
    FILE_INSPECTION = "FILE_INSPECTION"
    REVIEW_RESULT = "REVIEW_RESULT"
    HUMAN_APPROVAL = "HUMAN_APPROVAL"
    ACCEPTANCE_CRITERION_CHECK = "ACCEPTANCE_CRITERION_CHECK"


class AuditEventType(str, Enum):
    USER_STORY_CREATED = "USER_STORY_CREATED"
    STATE_CHANGED = "STATE_CHANGED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_FINISHED = "EXECUTION_FINISHED"
    EVIDENCE_PRODUCED = "EVIDENCE_PRODUCED"
    GATE_EVALUATED = "GATE_EVALUATED"
    REJECTION_RECORDED = "REJECTION_RECORDED"
    REMEDIATION_RECORDED = "REMEDIATION_RECORDED"
    HUMAN_APPROVAL_RECORDED = "HUMAN_APPROVAL_RECORDED"
    CERTIFICATION_GRANTED = "CERTIFICATION_GRANTED"
    CERTIFICATION_REFUSED = "CERTIFICATION_REFUSED"
    CERTIFICATION_BLOCKED = "CERTIFICATION_BLOCKED"


class MissionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MissionRole(str, Enum):
    ORCHESTRATOR = "ORCHESTRATOR"
    ARCHITECT = "ARCHITECT"
    IMPLEMENTER = "IMPLEMENTER"
    TESTER = "TESTER"
    REVIEWER = "REVIEWER"
    CERTIFIER = "CERTIFIER"


class OperatingStep(str, Enum):
    RECONSTRUCT = "RECONSTRUCT"
    PREFLIGHT = "PREFLIGHT"
    UNDERSTAND_CONTRACT = "UNDERSTAND_CONTRACT"
    PROVE_READINESS = "PROVE_READINESS"
    ACT = "ACT"
    VERIFY = "VERIFY"
    RECORD_EVIDENCE = "RECORD_EVIDENCE"
    CONTROLLED_TRANSITION = "CONTROLLED_TRANSITION"
    REPORT = "REPORT"
